#ifndef __SEED_FLAGS_H__
#define __SEED_FLAGS_H__

#define SEED_LF_CPU 1
#define SEED_LF_TIME 2
#define SEED_LF_ALL SEED_LF_CPU|SEED_LF_TIME

#define SEED_UNTRUSTED_LIBRARY 1
#define SEED_TRUSTED_LIBRARY 2

#endif /* __SEED_FLAGS_H__ */
