CC      = gcc
LD      = ld
AR      = ar
NM      = nm
OBJCOPY = objcopy
OBJDUMP = objdump
READELF = readelf

SSL_EC_OBJS = ssl_ec_client.o

BINS = bssl_ec_client_x86_64

CFLAGS = -DLOGGER -DDEBUG -Wall -I../../boringssl/include
SSL_LDADD = -L../../boringssl/lib64_x86_64 -lcrypto -lssl -lpthread

.PHONY: all
all: bssl_ec_client_x86_64

bssl_ec_client_x86_64: $(SSL_EC_OBJS)
	$(CC) -o $@ $(SSL_EC_OBJS) $(SSL_LDADD)

ssl_ec_client.o:
	$(CC) $(CFLAGS) -c ssl_ec_client.c -o $@

.PHONY: clean
clean:
	rm -f $(SSL_EC_OBJS) $(BINS)
