# Install script for directory: /home/hwlee/boringssl/crypto

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/hwlee/boringssl/build_x86_64/crypto/stack/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/lhash/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/err/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/buf/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/base64/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/bytestring/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/pool/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/rc4/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/conf/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/chacha/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/poly1305/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/curve25519/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/digest_extra/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/cipher_extra/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/rand_extra/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/bio/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/bn_extra/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/obj/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/asn1/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/engine/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/dh/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/dsa/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/rsa_extra/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/ec_extra/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/ecdh_extra/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/ecdsa_extra/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/cmac/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/evp/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/hkdf/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/pem/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/x509/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/x509v3/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/pkcs7/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/pkcs8/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/test/cmake_install.cmake")
  include("/home/hwlee/boringssl/build_x86_64/crypto/fipsmodule/cmake_install.cmake")

endif()

