#ifndef __ERR_H__
#define __ERR_H__

#define SEED_SUCCESS 0
#define SEED_FAILURE -1
#define SEED_NEED_WRITE 1
#define SEED_INVALID_PLATFORM 2
#define SEED_INVALID_COMMAND 3

#ifdef PLATFORM_OPTEE
  #define SEED_ERROR_OUT_OF_MEMORY TEE_ERROR_OUT_OF_MEMORY
#elif PLATFORM_SGX
  #define SEED_ERROR_OUT_OF_MEMORY 4
#endif /* PLATFORM ERROR */

#ifdef PLATFORM_OPTEE
  #define SEED_ERROR_BAD_STATE TEE_ERROR_BAD_STATE
#elif PLATFORM_SGX
  #define SEED_ERROR_BAD_STATE 5
#endif /* PLATFORM ERROR */

#ifdef PLATFORM_OPTEE
  #define SEED_ERROR_BAD_PARAMETERS TEE_ERROR_BAD_PARAMETERS
#elif PLATFORM_SGX
  #define SEED_ERROR_BAD_PARAMETERS 6
#endif /* PLATFORM ERROR */

// Platform specific errors
#ifdef PLATFORM_VANILA
  #define SEED_ERR_INVALID_CERT_PATH 1
  #define SEED_ERR_INVALID_KEY_PATH 2
#endif /* PLATFORM_VANILA */

#ifdef PLATFORM_SGX
  #define SEED_ERR_INVALID_ENCLAVE_PATH 1
#endif /* PLATFORM_SGX */

#define SEED_ERR_INVALID_MESSAGES_PATH 4
#define SEED_ERR_MODE_NONE  8

#define SEED_NEED_FALLBACK 255

#endif /* __ERR_H__ */
